import { Link } from 'react-router-dom'; import { ArrowRight, Clock3, Users } from 'lucide-react'; import { mediaUrl } from '../services/contentApi';
export const normalizeContentType = t => String(t || 'Article').trim().toLowerCase().replace(/[_\s]+/g, '-');
export const contentTypeLabel = t => ({ article: 'Article', 'technology-video': 'Technology Video', event: 'Event', 'company-update': 'Company Update', announcement: 'Announcement' }[normalizeContentType(t)] || 'Article');
export const contentAction = t => ({ 'article': 'Read Article', 'technology-video': 'Watch Video', 'event': 'View Highlights', 'company-update': 'Read Update', 'announcement': 'Read Announcement' }[t] || 'Read Article');
export const displayCategory = x => x.category === 'Other' ? (x.customCategory || 'Other') : (x.category || 'General'); export const formatDate = v => v ? new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(v)) : ''; export const getSkills = x => Array.isArray(x.skills) ? x.skills : Array.isArray(x.tags) ? x.tags : typeof x.skills === 'string' ? x.skills.split(',').map(s => s.trim()).filter(Boolean) : [];
export function PageHero({ eyebrow, title, description }) { return <section className="page-hero"><div className="page-hero-glow" /><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></section> }
export function CourseCard({ course }) { const o = Number(course.originalPrice ?? course.price ?? 0), p = Number(course.offerPrice ?? course.price ?? 0); return <article className="content-card"><div className="card-media"><img src={mediaUrl(course.image)} alt={course.title || 'Course'} loading="lazy" />{course.badge && <span className="media-badge">{course.badge}</span>}</div><div className="card-body"><div className="meta-line"><span>{displayCategory(course)}</span><span>{course.level || 'All Levels'}</span></div><h3>{course.title}</h3><p>{course.description}</p><div className="skills-row">{getSkills(course).slice(0, 4).map(s => <span key={s}>{s}</span>)}</div><div className="course-stats"><span><Clock3 /> {course.duration || 'Flexible'}</span><span><Users /> {Number(course.enrolled || 0)} enrolled</span></div><div className="card-footer"><div className="price"><small>Offer Price</small><strong>₹{p.toLocaleString('en-IN')}</strong>{o > p && <del>₹{o.toLocaleString('en-IN')}</del>}</div><Link className="card-link" to={`/courses/${course.slug || course._id}`}>View Course <ArrowRight /></Link></div></div></article> }
export function NewsCard({ item }) { return <article className="content-card"><div className="card-media"><img src={mediaUrl(item.thumbnailUrl || item.image || item.galleryImages?.[0])} alt={item.title || 'News & Insights'} loading="lazy" /><span className="media-badge">{contentTypeLabel(item.contentType)}</span></div><div className="card-body"><div className="meta-line"><span>{displayCategory(item)}</span>{item.eventDate && <span>{formatDate(item.eventDate)}</span>}</div><h3>{item.title}</h3><p>{item.description}</p><div className="card-footer"><small>{item.author?.name || item.authorName || 'ProJenius Team'}</small><Link className="card-link" to={`/insights/${item.slug || item._id}`}>{contentAction(item.contentType)} <ArrowRight /></Link></div></div></article> }
export function LoadingGrid() { return <div className="card-grid">{[1, 2, 3].map(i => <div className="skeleton-card" key={i}><div className="skeleton-media" /><div className="skeleton-lines"><i /><i /><i /></div></div>)}</div> }; export function ErrorState({ message, onRetry }) { return <div className="state-box"><strong>We couldn't load this content.</strong><p>{message}</p>{onRetry && <button onClick={onRetry}>Try Again</button>}</div> }; export function EmptyState({ label }) { return <div className="state-box"><strong>No {label} available yet.</strong><p>Published content from the ProJenius admin will appear here automatically.</p></div> }
